/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/*
 * @author BRYAN_CABRERA
 */
public class ModificarSecretaria extends javax.swing.JInternalFrame {

 
    /**
     * Creates new form ModificacionSecretaria
     */
    
    public static String x;

    public ModificarSecretaria() {
        initComponents();
        tablepersona.getTableHeader().setResizingAllowed(false);
        tablepersona.getTableHeader().setReorderingAllowed(false);
        x = "x";
        int a = MenuInicio.escritorio.getWidth() - this.getWidth();
        int b = MenuInicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        laregistro = new javax.swing.JLabel();
        lacedula = new javax.swing.JLabel();
        lacelular = new javax.swing.JLabel();
        lanombre = new javax.swing.JLabel();
        lacorreo = new javax.swing.JLabel();
        laapellido = new javax.swing.JLabel();
        ladireccion = new javax.swing.JLabel();
        lafecha_nac = new javax.swing.JLabel();
        laestado = new javax.swing.JLabel();
        lahorario = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        cbestado = new javax.swing.JComboBox<>();
        btnelimina = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        nacimeinto = new javax.swing.JTextField();
        lanombre1 = new javax.swing.JLabel();
        lacorreo1 = new javax.swing.JLabel();
        laestado1 = new javax.swing.JLabel();
        lacelular1 = new javax.swing.JLabel();
        lahorario1 = new javax.swing.JLabel();
        ladireccion1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepersona = new javax.swing.JTable();
        correo = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        btnimagen = new javax.swing.JButton();
        lafoto = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MODIFICAR Y ELIMINAR SECRETARIA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laregistro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        laregistro.setText("Modificar Informacion");
        jPanel1.add(laregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 30));

        lacedula.setText("Cedula:");
        jPanel1.add(lacedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        lacelular.setText("Celular:");
        jPanel1.add(lacelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 20));

        lanombre.setText("Nombre:");
        jPanel1.add(lanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        lacorreo.setText("Correo Electronico:");
        jPanel1.add(lacorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 20));

        laapellido.setText("Apellido:");
        jPanel1.add(laapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        ladireccion.setText("Direccion:");
        jPanel1.add(ladireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 60, 20));

        lafecha_nac.setText("Fecha de Nacimiento:");
        jPanel1.add(lafecha_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, 20));

        laestado.setText("Estado civil:");
        jPanel1.add(laestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 20));

        lahorario.setText("Registro de horario:");
        jPanel1.add(lahorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, 20));
        jPanel1.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 139, -1));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 139, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, -1, 40));

        jPanel1.add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 140, -1));

        btnelimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        btnelimina.setText("ELIMINAR REGISTRO");
        jPanel1.add(btnelimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, -1, 40));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 139, -1));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 139, -1));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 140, -1));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 139, -1));

        cb1.setText("9:00-13:00");
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        cb2.setText("13:00-15:00");
        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        cb3.setText("15:00-16:30");
        jPanel1.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        cb4.setText("16:30-18:30");
        jPanel1.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));
        jPanel1.add(nacimeinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 140, -1));

        lanombre1.setBackground(new java.awt.Color(255, 255, 255));
        lanombre1.setForeground(new java.awt.Color(255, 0, 0));
        lanombre1.setText("*Campo Obligatorio");
        jPanel1.add(lanombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        lacorreo1.setBackground(new java.awt.Color(255, 255, 255));
        lacorreo1.setForeground(new java.awt.Color(255, 0, 0));
        lacorreo1.setText("*Campo Obligatorio");
        jPanel1.add(lacorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        laestado1.setBackground(new java.awt.Color(255, 255, 255));
        laestado1.setForeground(new java.awt.Color(255, 0, 0));
        laestado1.setText("*Campo Obligatorio");
        jPanel1.add(laestado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        lacelular1.setBackground(new java.awt.Color(255, 255, 255));
        lacelular1.setForeground(new java.awt.Color(255, 0, 0));
        lacelular1.setText("*Campo Obligatorio");
        jPanel1.add(lacelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        lahorario1.setBackground(new java.awt.Color(255, 255, 255));
        lahorario1.setForeground(new java.awt.Color(255, 0, 0));
        lahorario1.setText("*Campo Obligatorio");
        jPanel1.add(lahorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        ladireccion1.setBackground(new java.awt.Color(255, 255, 255));
        ladireccion1.setForeground(new java.awt.Color(255, 0, 0));
        ladireccion1.setText("*Campo Obligatorio");
        jPanel1.add(ladireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        tablepersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablepersona);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 880, 180));

        correo.setBackground(new java.awt.Color(255, 255, 255));
        correo.setForeground(new java.awt.Color(255, 0, 0));
        correo.setText("*Correo Erroneo");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, -1));

        celular.setForeground(new java.awt.Color(255, 0, 0));
        celular.setText("*Telefono Erroneo");
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, -1));

        btnimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto.png"))); // NOI18N
        btnimagen.setText("FOTO");
        jPanel1.add(btnimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));
        jPanel1.add(lafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 130, 140));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 230, -1));

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("BUSCAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 70, 20));

        btncancelar.setText("CANCELAR");
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_pantalla.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1000, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btnelimina;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnimagen;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JCheckBox cb1;
    public javax.swing.JCheckBox cb2;
    public javax.swing.JCheckBox cb3;
    public javax.swing.JCheckBox cb4;
    public javax.swing.JComboBox<String> cbestado;
    public javax.swing.JLabel celular;
    public javax.swing.JLabel correo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel laapellido;
    public javax.swing.JLabel lacedula;
    public javax.swing.JLabel lacelular;
    public javax.swing.JLabel lacelular1;
    public javax.swing.JLabel lacorreo;
    public javax.swing.JLabel lacorreo1;
    public javax.swing.JLabel ladireccion;
    public javax.swing.JLabel ladireccion1;
    public javax.swing.JLabel laestado;
    public javax.swing.JLabel laestado1;
    public javax.swing.JLabel lafecha_nac;
    public javax.swing.JLabel lafoto;
    public javax.swing.JLabel lahorario;
    public javax.swing.JLabel lahorario1;
    public javax.swing.JLabel lanombre;
    public javax.swing.JLabel lanombre1;
    public javax.swing.JLabel laregistro;
    public javax.swing.JTextField nacimeinto;
    public javax.swing.JTable tablepersona;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtcedula;
    public javax.swing.JTextField txtcelular;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
