/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author BRYAN_CABRERA
 */
public class RegistroAbogado extends javax.swing.JInternalFrame {
    
    public static String x;

    /**
     * Creates new form Abogados
     */

    public RegistroAbogado() {
        initComponents();
        x = "x";
        int a = MenuInicio.escritorio.getWidth() - this.getWidth();
        int b = MenuInicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lacampo10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        laregistro = new javax.swing.JLabel();
        lacedula = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lacelular = new javax.swing.JLabel();
        lanombre = new javax.swing.JLabel();
        lacorreo = new javax.swing.JLabel();
        laapellido = new javax.swing.JLabel();
        ladireccion = new javax.swing.JLabel();
        lafecha_nac = new javax.swing.JLabel();
        laestado = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        lanum_matri = new javax.swing.JLabel();
        lanum_cuenta = new javax.swing.JLabel();
        lahorario = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtmatricula = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtcuenta = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbestado = new javax.swing.JComboBox<>();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        btnnuevo = new javax.swing.JButton();
        lanombre1 = new javax.swing.JLabel();
        laapellido1 = new javax.swing.JLabel();
        lacedula1 = new javax.swing.JLabel();
        lacelular1 = new javax.swing.JLabel();
        ladireccion1 = new javax.swing.JLabel();
        lacorreo1 = new javax.swing.JLabel();
        lafecha = new javax.swing.JLabel();
        laestado1 = new javax.swing.JLabel();
        lacuenta1 = new javax.swing.JLabel();
        lamatricula1 = new javax.swing.JLabel();
        lahorario1 = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        lafoto = new javax.swing.JLabel();
        btnimagen = new javax.swing.JButton();
        datomatricula = new javax.swing.JLabel();
        datocorreo = new javax.swing.JLabel();
        datocedula = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lacampo10.setBackground(new java.awt.Color(255, 255, 255));
        lacampo10.setForeground(new java.awt.Color(255, 0, 0));
        lacampo10.setText("*Campo Obligatorio");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REGISTRO ABOGADO");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laregistro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        laregistro.setText("Registro de Abogado");
        jPanel1.add(laregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));

        lacedula.setText("Cedula:");
        jPanel1.add(lacedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 145, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 132, -1));

        lacelular.setText("Celular:");
        jPanel1.add(lacelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));

        lanombre.setText("Nombre:");
        jPanel1.add(lanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        lacorreo.setText("Correo Electronico:");
        jPanel1.add(lacorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 20));

        laapellido.setText("Apellido:");
        jPanel1.add(laapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        ladireccion.setText("Direccion:");
        jPanel1.add(ladireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 20));

        lafecha_nac.setText("Fecha de Nacimiento:");
        jPanel1.add(lafecha_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 20));

        laestado.setText("Estado civil:");
        jPanel1.add(laestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 20));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 132, -1));

        lanum_matri.setText("Numero de Matricula:");
        jPanel1.add(lanum_matri, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 25));

        lanum_cuenta.setText("Numero de Cuenta:");
        jPanel1.add(lanum_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, 20));

        lahorario.setText("Registro de horario:");
        jPanel1.add(lahorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, 20));
        jPanel1.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, -1));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 130, -1));
        jPanel1.add(txtmatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 145, -1));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 130, -1));
        jPanel1.add(txtcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 145, -1));

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 130, 40));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 120, 40));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 145, -1));

        jPanel1.add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 145, -1));

        cb1.setText("9:00-13:00");
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 90, -1));

        cb2.setText("13:00-15:00");
        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        cb3.setText("15:00-16:30");
        jPanel1.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        cb4.setText("16:30-18:30");
        jPanel1.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnnuevo.setText("NUEVO");
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        lanombre1.setBackground(new java.awt.Color(255, 255, 255));
        lanombre1.setForeground(new java.awt.Color(255, 0, 0));
        lanombre1.setText("*Campo Obligatorio");
        jPanel1.add(lanombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 10));

        laapellido1.setBackground(new java.awt.Color(255, 255, 255));
        laapellido1.setForeground(new java.awt.Color(255, 0, 0));
        laapellido1.setText("*Campo Obligatorio");
        jPanel1.add(laapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lacedula1.setBackground(new java.awt.Color(255, 255, 255));
        lacedula1.setForeground(new java.awt.Color(255, 0, 0));
        lacedula1.setText("*Campo Obligatorio");
        jPanel1.add(lacedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        lacelular1.setBackground(new java.awt.Color(255, 255, 255));
        lacelular1.setForeground(new java.awt.Color(255, 0, 0));
        lacelular1.setText("*Campo Obligatorio");
        jPanel1.add(lacelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        ladireccion1.setBackground(new java.awt.Color(255, 255, 255));
        ladireccion1.setForeground(new java.awt.Color(255, 0, 0));
        ladireccion1.setText("*Campo Obligatorio");
        jPanel1.add(ladireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        lacorreo1.setBackground(new java.awt.Color(255, 255, 255));
        lacorreo1.setForeground(new java.awt.Color(255, 0, 0));
        lacorreo1.setText("*Campo Obligatorio");
        jPanel1.add(lacorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lafecha.setBackground(new java.awt.Color(255, 255, 255));
        lafecha.setForeground(new java.awt.Color(255, 0, 0));
        lafecha.setText("*Campo Obligatorio");
        jPanel1.add(lafecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        laestado1.setBackground(new java.awt.Color(255, 255, 255));
        laestado1.setForeground(new java.awt.Color(255, 0, 0));
        laestado1.setText("*Campo Obligatorio");
        jPanel1.add(laestado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        lacuenta1.setBackground(new java.awt.Color(255, 255, 255));
        lacuenta1.setForeground(new java.awt.Color(255, 0, 0));
        lacuenta1.setText("*Campo Obligatorio");
        jPanel1.add(lacuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        lamatricula1.setBackground(new java.awt.Color(255, 255, 255));
        lamatricula1.setForeground(new java.awt.Color(255, 0, 0));
        lamatricula1.setText("*Campo Obligatorio");
        jPanel1.add(lamatricula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        lahorario1.setBackground(new java.awt.Color(255, 255, 255));
        lahorario1.setForeground(new java.awt.Color(255, 0, 0));
        lahorario1.setText("*Campo Obligatorio");
        jPanel1.add(lahorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        correo.setBackground(new java.awt.Color(255, 255, 255));
        correo.setForeground(new java.awt.Color(255, 0, 0));
        correo.setText("*Correo Erroneo");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 110, -1));

        celular.setForeground(new java.awt.Color(255, 0, 0));
        celular.setText("*Telefono Erroneo");
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        cedula.setForeground(new java.awt.Color(255, 0, 0));
        cedula.setText("*Cedula Erronea");
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));
        jPanel1.add(lafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 160, 170));

        btnimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Foto.png"))); // NOI18N
        btnimagen.setText("FOTO");
        jPanel1.add(btnimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        datomatricula.setForeground(new java.awt.Color(255, 0, 0));
        datomatricula.setText("*Dato Existente");
        jPanel1.add(datomatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        datocorreo.setForeground(new java.awt.Color(255, 0, 0));
        datocorreo.setText("*Dato Existente");
        jPanel1.add(datocorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        datocedula.setForeground(new java.awt.Color(255, 0, 0));
        datocedula.setText("*Dato Existente");
        jPanel1.add(datocedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        foto.setBackground(new java.awt.Color(255, 255, 255));
        foto.setForeground(new java.awt.Color(255, 0, 0));
        foto.setText("*Campo Obligatorio");
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_pantalla.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnimagen;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JCheckBox cb1;
    public javax.swing.JCheckBox cb2;
    public javax.swing.JCheckBox cb3;
    public javax.swing.JCheckBox cb4;
    public javax.swing.JComboBox<String> cbestado;
    public javax.swing.JLabel cedula;
    public javax.swing.JLabel celular;
    public javax.swing.JLabel correo;
    public javax.swing.JLabel datocedula;
    public javax.swing.JLabel datocorreo;
    public javax.swing.JLabel datomatricula;
    public javax.swing.JLabel foto;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laapellido;
    public javax.swing.JLabel laapellido1;
    private javax.swing.JLabel lacampo10;
    private javax.swing.JLabel lacedula;
    public javax.swing.JLabel lacedula1;
    private javax.swing.JLabel lacelular;
    public javax.swing.JLabel lacelular1;
    private javax.swing.JLabel lacorreo;
    public javax.swing.JLabel lacorreo1;
    public javax.swing.JLabel lacuenta1;
    private javax.swing.JLabel ladireccion;
    public javax.swing.JLabel ladireccion1;
    private javax.swing.JLabel laestado;
    public javax.swing.JLabel laestado1;
    public javax.swing.JLabel lafecha;
    private javax.swing.JLabel lafecha_nac;
    public javax.swing.JLabel lafoto;
    private javax.swing.JLabel lahorario;
    public javax.swing.JLabel lahorario1;
    public javax.swing.JLabel lamatricula1;
    private javax.swing.JLabel lanombre;
    public javax.swing.JLabel lanombre1;
    private javax.swing.JLabel lanum_cuenta;
    private javax.swing.JLabel lanum_matri;
    private javax.swing.JLabel laregistro;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtcedula;
    public javax.swing.JTextField txtcelular;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtcuenta;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtmatricula;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
