/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class RequisitosEstadosUnidos extends javax.swing.JInternalFrame {
   
    public static String x;

    /**
     * Creates new form RequisitosEstadosUnidos
     */

    public RequisitosEstadosUnidos() {
        initComponents();
        
        setTitle("TRAMITES DE VISA");
        x = "x";
        int a = MenuInicio.escritorio.getWidth() - this.getWidth();
        int b = MenuInicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rq1 = new javax.swing.JCheckBox();
        rq2 = new javax.swing.JCheckBox();
        rq4 = new javax.swing.JCheckBox();
        rq6 = new javax.swing.JCheckBox();
        rq3 = new javax.swing.JCheckBox();
        rq11 = new javax.swing.JCheckBox();
        rq5 = new javax.swing.JCheckBox();
        rq8 = new javax.swing.JCheckBox();
        rq10 = new javax.swing.JCheckBox();
        comboNum = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        honorarios = new javax.swing.JLabel();
        rq9 = new javax.swing.JCheckBox();
        rq7 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnmoficar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_pago = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VISA ESTADOS UNIDOS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REQUISITOS VISA EEUU ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 19, -1, -1));

        rq1.setText("PASAPORTE");
        jPanel1.add(rq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        rq2.setText("COPIA DE CEDULA");
        jPanel1.add(rq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        rq4.setText("PARTIDA DE MATRIMONIO");
        jPanel1.add(rq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        rq6.setText("FOTOS 5 x 5 ");
        jPanel1.add(rq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        rq3.setText("PARTIDAS DE NACIMIENTOS ");
        jPanel1.add(rq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        rq11.setText("PREDIOS");
        jPanel1.add(rq11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        rq5.setText("DIRECCION DE LOS EEUU");
        jPanel1.add(rq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        rq8.setText("CERTIFICADOS BANCARIOS");
        jPanel1.add(rq8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        rq10.setText("CERTIFICADO DE ESTUDIO");
        jPanel1.add(rq10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jPanel1.add(comboNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 67, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NUMERO DE BENEFICIARIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 467, -1));

        jLabel3.setText("OBSERVACIONES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        honorarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        honorarios.setForeground(new java.awt.Color(51, 0, 0));
        honorarios.setText("HONORARIOS: 90 POR PERSONA");
        jPanel1.add(honorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        rq9.setText("CERTIFICADO DE TRABAJO");
        jPanel1.add(rq9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        rq7.setText("MATRICULA DE VEHICULO");
        jPanel1.add(rq7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_pantalla.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 668, 398));

        btnmoficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnmoficar.setText("MODIFICAR");
        getContentPane().add(btnmoficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        btn_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagar.png"))); // NOI18N
        btn_pago.setText("PAGO");
        getContentPane().add(btn_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_guardar;
    public javax.swing.JButton btn_pago;
    public javax.swing.JButton btnmoficar;
    public javax.swing.JComboBox<String> comboNum;
    public javax.swing.JLabel honorarios;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea observaciones;
    public javax.swing.JCheckBox rq1;
    public javax.swing.JCheckBox rq10;
    public javax.swing.JCheckBox rq11;
    public javax.swing.JCheckBox rq2;
    public javax.swing.JCheckBox rq3;
    public javax.swing.JCheckBox rq4;
    public javax.swing.JCheckBox rq5;
    public javax.swing.JCheckBox rq6;
    public javax.swing.JCheckBox rq7;
    public javax.swing.JCheckBox rq8;
    public javax.swing.JCheckBox rq9;
    // End of variables declaration//GEN-END:variables
}
