/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class RequisitosReporteConsular extends javax.swing.JInternalFrame {

    public static String x;

    /**
     * Creates new form RequisitosReporteConsular
     */
    public RequisitosReporteConsular() {
        initComponents();
        x = "x";
        int a = MenuInicio.escritorio.getWidth() - this.getWidth();
        int b = MenuInicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rq1 = new javax.swing.JCheckBox();
        rq4 = new javax.swing.JCheckBox();
        rq5 = new javax.swing.JCheckBox();
        rq3 = new javax.swing.JCheckBox();
        rq2 = new javax.swing.JCheckBox();
        rq6 = new javax.swing.JCheckBox();
        comboNum = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        honorarios = new javax.swing.JLabel();
        rq8 = new javax.swing.JCheckBox();
        rq7 = new javax.swing.JCheckBox();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btn_pago = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REPORTE CONSULAR");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REQUISITOS REPORTE CONSULAR  DE NACIMIENTO ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 19, -1, -1));

        rq1.setText("DS-2029");
        jPanel2.add(rq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 66, -1, -1));

        rq4.setText("CERTIFICADO NATURALIZACION");
        jPanel2.add(rq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 189, -1, -1));

        rq5.setText("INSCRIPCION DE NACIMIENTO");
        jPanel2.add(rq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 227, -1, -1));

        rq3.setText("PRUEBA DE CIUDADANIA");
        jPanel2.add(rq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 148, -1, -1));

        rq2.setText("DS- 11");
        jPanel2.add(rq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 107, -1, -1));

        rq6.setText("DIRECCION EN LOS EEUU");
        jPanel2.add(rq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jPanel2.add(comboNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NUMERO DE PERSONAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 71, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 329, 456, -1));

        jLabel3.setText("OBSERVACIONES:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 309, -1, -1));

        honorarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        honorarios.setForeground(new java.awt.Color(51, 0, 0));
        honorarios.setText("HONORARIOS: 250 POR PERSONA");
        jPanel2.add(honorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        rq8.setText("REGISTRO DE VACUNAS");
        jPanel2.add(rq8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 148, -1, -1));

        rq7.setText("RECORD MEDICOS");
        jPanel2.add(rq7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 107, -1, -1));

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        jPanel2.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        btn_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagar.png"))); // NOI18N
        btn_pago.setText("PAGO");
        jPanel2.add(btn_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_pantalla.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 700, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_pago;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JComboBox<String> comboNum;
    public javax.swing.JLabel honorarios;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea observaciones;
    public javax.swing.JCheckBox rq1;
    public javax.swing.JCheckBox rq2;
    public javax.swing.JCheckBox rq3;
    public javax.swing.JCheckBox rq4;
    public javax.swing.JCheckBox rq5;
    public javax.swing.JCheckBox rq6;
    public javax.swing.JCheckBox rq7;
    public javax.swing.JCheckBox rq8;
    // End of variables declaration//GEN-END:variables
}
