/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/*
 * @author BRYAN_CABRERA
 */
public class RequisitosLoteria extends javax.swing.JInternalFrame {

    public static String x;

    public RequisitosLoteria() {
        initComponents();
        x = "x";
        setTitle("TRAMITES DE VISAS");
        int a = MenuInicio.escritorio.getWidth() - this.getWidth();
        int b = MenuInicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rq2 = new javax.swing.JCheckBox();
        rq1 = new javax.swing.JCheckBox();
        rq4 = new javax.swing.JCheckBox();
        rq3 = new javax.swing.JCheckBox();
        rq5 = new javax.swing.JCheckBox();
        rq8 = new javax.swing.JCheckBox();
        rq7 = new javax.swing.JCheckBox();
        rq9 = new javax.swing.JCheckBox();
        rq6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboNum = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        honorarios = new javax.swing.JLabel();
        btn_pago = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rq2.setText("PARTIDA DE NACIMIENTOS");
        jPanel1.add(rq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        rq1.setText("PASAPORTE");
        jPanel1.add(rq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        rq4.setText("DATOS DE ESTUDIOS");
        jPanel1.add(rq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        rq3.setText("PARTIDA DE MATRIMONIO");
        jPanel1.add(rq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        rq5.setText("DATOS DE PADRES");
        jPanel1.add(rq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        rq8.setText("FOTO DIGITAL 5 X5");
        jPanel1.add(rq8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        rq7.setText("DIRECCION DE LOS EEUU");
        jPanel1.add(rq7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        rq9.setText("DATOS DE TRABAJO");
        jPanel1.add(rq9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        rq6.setText("DATOS DE HERMANOS");
        jPanel1.add(rq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REQUISITOS VISA DE LOTERIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 420, 68));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NUMERO DE PERSONAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jPanel1.add(comboNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("OBSERVACIONES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane2.setViewportView(observaciones);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 510, -1));

        honorarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        honorarios.setForeground(new java.awt.Color(51, 0, 0));
        honorarios.setText("HONORARIOS: 40 POR PERSONA");
        jPanel1.add(honorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        btn_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagar.png"))); // NOI18N
        btn_pago.setText("PAGO");
        jPanel1.add(btn_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_pantalla.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 590, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_pago;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JComboBox<String> comboNum;
    public javax.swing.JLabel honorarios;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea observaciones;
    public javax.swing.JCheckBox rq1;
    public javax.swing.JCheckBox rq2;
    public javax.swing.JCheckBox rq3;
    public javax.swing.JCheckBox rq4;
    public javax.swing.JCheckBox rq5;
    public javax.swing.JCheckBox rq6;
    public javax.swing.JCheckBox rq7;
    public javax.swing.JCheckBox rq8;
    public javax.swing.JCheckBox rq9;
    // End of variables declaration//GEN-END:variables
}
