/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class V_Citas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cita
     */
    public static String x;

    public V_Citas() {
        
        initComponents();
        
        x = "x";
        int a = V_Menu_Inicio.escritorio.getWidth() - this.getWidth();
        int b = V_Menu_Inicio.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 5);
    }

    public static JButton getBtn_buscar() {
        return btn_buscar;
    }

    public static void setBtn_buscar(JButton btn_buscar) {
        V_Citas.btn_buscar = btn_buscar;
    }

    public static JButton getBtn_guardar() {
        return btn_guardar;
    }

    public static void setBtn_guardar(JButton btn_guardar) {
        V_Citas.btn_guardar = btn_guardar;
    }

    public static JLabel getCaso() {
        return caso;
    }

    public static void setCaso(JLabel caso) {
        V_Citas.caso = caso;
    }

    public static JComboBox<String> getCb_caso() {
        return cb_caso;
    }

    public static void setCb_caso(JComboBox<String> cb_caso) {
        V_Citas.cb_caso = cb_caso;
    }

    public static JLabel getCedula() {
        return cedula;
    }

    public static void setCedula(JLabel cedula) {
        V_Citas.cedula = cedula;
    }

    public static JLabel getCelular() {
        return celular;
    }

    public static void setCelular(JLabel celular) {
        V_Citas.celular = celular;
    }

    public static JLabel getDds() {
        return dds;
    }

    public static void setDds(JLabel dds) {
        V_Citas.dds = dds;
    }

    public static JLabel getDescripcion() {
        return descripcion;
    }

    public static void setDescripcion(JLabel descripcion) {
        V_Citas.descripcion = descripcion;
    }

    public static JLabel getHora() {
        return hora;
    }

    public static void setHora(JLabel hora) {
        V_Citas.hora = hora;
    }

    public static JLabel getjLabel1() {
        return jLabel1;
    }

    public static void setjLabel1(JLabel jLabel1) {
        V_Citas.jLabel1 = jLabel1;
    }

    public static JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static void setjScrollPane1(JScrollPane jScrollPane1) {
        V_Citas.jScrollPane1 = jScrollPane1;
    }

    public static JSpinner getJs_hora() {
        return js_hora;
    }

    public static void setJs_hora(JSpinner js_hora) {
        V_Citas.js_hora = js_hora;
    }

    public static JLabel getLb_caso() {
        return lb_caso;
    }

    public static void setLb_caso(JLabel lb_caso) {
        V_Citas.lb_caso = lb_caso;
    }

    public static JLabel getLb_cedula() {
        return lb_cedula;
    }

    public static void setLb_cedula(JLabel lb_cedula) {
        V_Citas.lb_cedula = lb_cedula;
    }

    public static JLabel getLb_celular() {
        return lb_celular;
    }

    public static void setLb_celular(JLabel lb_celular) {
        V_Citas.lb_celular = lb_celular;
    }

    public static JTextArea getTxa_descripcion() {
        return txa_descripcion;
    }

    public static void setTxa_descripcion(JTextArea txa_descripcion) {
        V_Citas.txa_descripcion = txa_descripcion;
    }

    public static JTextField getTxt_cedula() {
        return txt_cedula;
    }

    public static void setTxt_cedula(JTextField txt_cedula) {
        V_Citas.txt_cedula = txt_cedula;
    }

    public static JTextField getTxt_celular() {
        return txt_celular;
    }

    public static void setTxt_celular(JTextField txt_celular) {
        V_Citas.txt_celular = txt_celular;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_celular = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dds = new javax.swing.JLabel();
        caso = new javax.swing.JLabel();
        cb_caso = new javax.swing.JComboBox<>();
        descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_descripcion = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();
        hora = new javax.swing.JLabel();
        js_hora = new javax.swing.JSpinner();
        lb_cedula = new javax.swing.JLabel();
        lb_celular = new javax.swing.JLabel();
        lb_caso = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        cedula = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CITAS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 239, -1));

        jLabel1.setText("Cedula:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 20));

        dds.setText("Celular:");
        jPanel2.add(dds, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, 20));

        caso.setText("Caso:");
        jPanel2.add(caso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 20));

        cb_caso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(cb_caso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 239, -1));

        descripcion.setText("Descripcion:");
        jPanel2.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        txa_descripcion.setColumns(20);
        txa_descripcion.setLineWrap(true);
        txa_descripcion.setRows(5);
        jScrollPane1.setViewportView(txa_descripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 320, 120));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        jPanel2.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, 60));

        hora.setText("Hora:");
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 20));

        js_hora.setModel(new javax.swing.SpinnerDateModel());
        js_hora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        js_hora.setEditor(new javax.swing.JSpinner.DateEditor(js_hora, "dd/MM/yyyy HH:mm"));
        jPanel2.add(js_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lb_cedula.setBackground(new java.awt.Color(255, 255, 255));
        lb_cedula.setForeground(new java.awt.Color(255, 0, 0));
        lb_cedula.setText("*Campo Obligatorio");
        jPanel2.add(lb_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        lb_celular.setBackground(new java.awt.Color(255, 255, 255));
        lb_celular.setForeground(new java.awt.Color(255, 0, 0));
        lb_celular.setText("*Campo Obligatorio");
        jPanel2.add(lb_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 17));

        lb_caso.setBackground(new java.awt.Color(255, 255, 255));
        lb_caso.setForeground(new java.awt.Color(255, 0, 0));
        lb_caso.setText("*Campo Obligatorio");
        jPanel2.add(lb_caso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));
        jPanel2.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        jPanel2.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, 50));

        cedula.setForeground(new java.awt.Color(255, 0, 0));
        cedula.setText("*Cedula Erronea");
        jPanel2.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        celular.setForeground(new java.awt.Color(255, 0, 0));
        celular.setText("*Telefono Erroneo");
        jPanel2.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    public static javax.swing.JButton btn_guardar;
    public static javax.swing.JLabel caso;
    public static javax.swing.JComboBox<String> cb_caso;
    public static javax.swing.JLabel cedula;
    public static javax.swing.JLabel celular;
    public static javax.swing.JLabel dds;
    public static javax.swing.JLabel descripcion;
    public static javax.swing.JLabel hora;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JSpinner js_hora;
    public static javax.swing.JLabel lb_caso;
    public static javax.swing.JLabel lb_cedula;
    public static javax.swing.JLabel lb_celular;
    public static javax.swing.JTextArea txa_descripcion;
    public static javax.swing.JTextField txt_cedula;
    public static javax.swing.JTextField txt_celular;
    // End of variables declaration//GEN-END:variables
}
