/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author BRYAN_CABRERA
 */
public class V_RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form V_RecuperarContraseña
     */
    public V_RecuperarContraseña() {
        initComponents();
        setTitle("KarYaN");
    }

    public JButton getBtn_cancelar() {
        return btn_cancelar;
    }

    public void setBtn_cancelar(JButton btn_cancelar) {
        this.btn_cancelar = btn_cancelar;
    }

    public JButton getBtn_enviar() {
        return btn_enviar;
    }

    public void setBtn_enviar(JButton btn_enviar) {
        this.btn_enviar = btn_enviar;
    }

    public JLabel getLb_correo() {
        return lb_correo;
    }

    public void setLb_correo(JLabel lb_correo) {
        this.lb_correo = lb_correo;
    }

    public JLabel getLb_usuario() {
        return lb_usuario;
    }

    public void setLb_usuario(JLabel lb_usuario) {
        this.lb_usuario = lb_usuario;
    }

    public JLabel getLbl_cedula() {
        return lbl_cedula;
    }

    public void setLbl_cedula(JLabel lbl_cedula) {
        this.lbl_cedula = lbl_cedula;
    }

    public JLabel getLbl_registro() {
        return lbl_registro;
    }

    public void setLbl_registro(JLabel lbl_registro) {
        this.lbl_registro = lbl_registro;
    }

    public JLabel getLbl_usuario() {
        return lbl_usuario;
    }

    public void setLbl_usuario(JLabel lbl_usuario) {
        this.lbl_usuario = lbl_usuario;
    }

    public JTextField getTxt_correo() {
        return txt_correo;
    }

    public void setTxt_correo(JTextField txt_correo) {
        this.txt_correo = txt_correo;
    }

    public JTextField getTxt_usuario() {
        return txt_usuario;
    }

    public void setTxt_usuario(JTextField txt_usuario) {
        this.txt_usuario = txt_usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_registro = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        lb_usuario = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 131, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_registro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lbl_registro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registro.setText("RECUPERAR CONTRASEÑA");
        jPanel1.add(lbl_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));

        lbl_cedula.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        lbl_cedula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cedula.setText("USUARIO:");
        jPanel1.add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, 20));

        lbl_usuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("CORREO ELECTRONICO:");
        jPanel1.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 20));

        txt_correo.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 180, 30));

        btn_enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1492692368-7email_83536.png"))); // NOI18N
        btn_enviar.setText("ENVIAR");
        jPanel1.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 50));

        lb_usuario.setBackground(new java.awt.Color(255, 255, 255));
        lb_usuario.setForeground(new java.awt.Color(255, 0, 0));
        lb_usuario.setText("*Campo Obligatorio");
        jPanel1.add(lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        lb_correo.setBackground(new java.awt.Color(255, 255, 255));
        lb_correo.setForeground(new java.awt.Color(255, 0, 0));
        lb_correo.setText("*Campo Obligatorio");
        jPanel1.add(lb_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/vcsconflicting_93497.png"))); // NOI18N
        btn_cancelar.setText("CANCELAR");
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, 50));

        txt_usuario.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_registro;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
